In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("pre_chelsea_2017.csv")
df2= pd.read_csv("pre_chelsea_2022.csv")

In [4]:
print(df1.shape)
print(df2.shape)

(26009, 12)
(40128, 12)

In [5]:
# Convert election date column to datetime for consistency
df1['date'] = pd.to_datetime(df1['date'])

# Add a marker column to track turnout (can be 1 for each vote)
df1['voted'] = 1

# Pivot to wide format: one row per voter, one column per election date
pivot_df = df1.pivot_table(
    index=['voter_id_number', 'last_name', 'first_name', 'ward_number', 'precinct_number', 'census_tract', 'date_of_birth', 'date_of_registration', 'latitude', 'longitude'],
    columns='date',
    values='voted',
    fill_value=0
).reset_index()

# Optional: rename the date columns to string format
pivot_df.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in pivot_df.columns]

pivot_df.head()

,voter_id_number,last_name,first_name,ward_number,precinct_number,census_tract,date_of_birth,date_of_registration,latitude,longitude,...,2014-09-09,2014-11-04,2015-09-22,2015-11-03,2016-01-31,2016-03-01,2016-09-08,2016-11-08,2017-09-26,2017-11-07
0,01AAA3148000,ARSENAULT,ANITA,2,1,1603.00,1/31/1948,5/15/1988,42.389275,-71.047913,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,01AAE2867000,ADAMS,ANNIE,3,4,1605.01,1/28/1967,5/15/1972,42.397918,-71.031821,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,01AAI0361000,AHMETI,AJET,3,3,1605.01,1/3/1961,7/15/2005,42.398788,-71.031367,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,01AAL0367000,ARRIETA,ANGEL,3,2,1605.02,1/3/1967,10/25/2000,42.401759,-71.015497,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,01AAR0168001,ABDO,ABUCAR,1,3,1601.02,1/6/1968,1/2/2009,42.390557,-71.028516,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
pivot_df

,voter_id_number,last_name,first_name,ward_number,precinct_number,census_tract,date_of_birth,date_of_registration,latitude,longitude,...,2014-09-09,2014-11-04,2015-09-22,2015-11-03,2016-01-31,2016-03-01,2016-09-08,2016-11-08,2017-09-26,2017-11-07
0,01AAA3148000,ARSENAULT,ANITA,2,1,1603.00,1/31/1948,5/15/1988,42.389275,-71.047913,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,01AAE2867000,ADAMS,ANNIE,3,4,1605.01,1/28/1967,5/15/1972,42.397918,-71.031821,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,01AAI0361000,AHMETI,AJET,3,3,1605.01,1/3/1961,7/15/2005,42.398788,-71.031367,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,01AAL0367000,ARRIETA,ANGEL,3,2,1605.02,1/3/1967,10/25/2000,42.401759,-71.015497,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,01AAR0168001,ABDO,ABUCAR,1,3,1601.02,1/6/1968,1/2/2009,42.390557,-71.028516,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6199,12YGS0762002,YUMAN,GLADIS,4,2,1606.02,12/7/1962,4/25/2011,42.405646,-71.030510,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
6200,12YJN1366000,YOUNG,JOHN,2,4,1604.00,12/13/1966,10/5/2008,42.390377,-71.038506,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
6201,12ZAA0196002,ZARNI,AMANDA,4,1,1605.02,12/1/1996,10/14/2016,42.401278,-71.020431,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6202,12ZDL1977000,ZAPATA,DANIEL,1,1,1601.03,12/19/1977,9/21/1996,42.388100,-71.031791,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6203,12ZIO0543001,ZALDANA,ISIDRO,2,1,1603.00,12/5/1943,9/3/2015,42.390148,-71.045926,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0